### ISSUE TITLE
Cloning repo + adding to website doesn't seem to work

### ISSUE THREAD

**Issue by Miskerest** [Ezcha/Don-t-Push-the-Button#4]
I'm not much of a web dev so I can't help too much, but just cloning it into my apache2 server doesn't seem to work. Are there some dependencies? 

For reference, I'm hosting it here: https://misker.xyz/button/index.html

edit: saw your post on reddit by the way. RIP /r/thebutton

**Comment by Ezcha** [comment]
You have to run index.js with node. https://nodejs.org/en/ This node server will deliver the page to anyone who connects.

**Comment by Miskerest** [comment]
Oh, duh. That might explain the "node" directory.
