### ISSUE TITLE
events.js:160 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by Miskerest** [Ezcha/Don-t-Push-the-Button#5]
Running this on Debian 8, node v. 6.2.2, npm v. 3.9.5. Starting the script with node yields an error, apparently with `events.js`. I'm guessing it's a node.js module? Here's the output that follows:

```
$ node index.js 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at Server._listen2 (net.js:1240:19)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at Object.<anonymous> (/var/www/html/button/index.js:22:6)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

**Comment by Ezcha** [comment]
Try running "npm install" in the directory.

**Comment by Miskerest** [comment]
I got it to run after changing `var port = 80;` in index.js to `var port = 8000;` 
However, when navigating to the site at port 8000 I get a 404, and without it, the script doesn't run.

**Comment by Miskerest** [comment]
For reference, this is stdout:

```
$ sudo node index.js 
listening on *: 8000
```

**Comment by Miskerest** [comment]
I was looking in the wrong place. I had `index.js` in a subdirectory on my webserver and was trying to access it there. Running it on an unprivileged port and appending it to the root of my website made it work fine.

If you'd like to see: http://www.misker.xyz:9000

**Comment by Miskerest** [comment]
Perhaps adding some sort of open/closed socket detection for port 80 would make it easier to add to an existing webserver? Then make it clear that it's running on port X on stdout when setting up, so that admins can point links to the correct port/address.
